#!/usr/bin/env python3
"""Generate the parameter, spot value and enumeration reference pages.

Usage:
    python3 scripts/gen_param_reference.py /path/to/Stm32-vcu

Reads include/param_prj.h from a checkout of damienmaguire/Stm32-vcu and
rewrites docs/reference/parameters.md, spot-values.md and enums.md. The
descriptions live in scripts/param_descriptions.py so they survive a
regeneration; anything the firmware adds that has no description shows up
as "(undocumented)" so it is easy to spot.
"""

import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from param_descriptions import PARAM_DESC, VALUE_DESC  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "reference"


def load_header(repo: Path) -> str:
    text = (repo / "include" / "param_prj.h").read_text()
    # drop comments (the header keeps retired params in a commented block)
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//[^\n]*", "", text)
    # join backslash continuations so every #define / entry is one line
    return re.sub(r"\\\s*\n", " ", text)


def parse_defines(text: str) -> dict:
    defines = {}
    for m in re.finditer(r"#define\s+(\w+)\s+((?:\"[^\"]*\"\s*)+)", text):
        parts = re.findall(r"\"([^\"]*)\"", m.group(2))
        defines[m.group(1)] = "".join(parts)
    return defines


def parse_entries(text: str):
    params, values = [], []
    for m in re.finditer(
        r"PARAM_ENTRY\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(\"[^\"]*\"|\w+)\s*,"
        r"\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*(\d+)\s*\)",
        text,
    ):
        params.append(m.groups())
    for m in re.finditer(r"VALUE_ENTRY\(\s*(\w+)\s*,\s*(\"[^\"]*\"|\w+)\s*,\s*(\d+)\s*\)", text):
        values.append(m.groups())
    return params, values


def unit_text(unit: str, defines: dict):
    """Return (display unit, enum options or None)."""
    if unit.startswith('"'):
        return unit.strip('"'), None
    resolved = defines.get(unit, unit)
    if "=" in resolved:
        return f"`{unit}`", resolved
    return resolved, None


def fmt_options(opts: str) -> str:
    items = [o.strip() for o in re.split(r"[,.]\s*(?=-?\d+=)", opts) if o.strip()]
    return "<br>".join(f"`{i}`" for i in items)


def esc(s: str) -> str:
    return s.replace("|", "\\|")


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    repo = Path(sys.argv[1])
    text = load_header(repo)
    defines = parse_defines(text)
    params, values = parse_entries(text)
    version = re.search(r"#define\s+VER\s+(\S+)", text).group(1)
    try:
        commit = subprocess.check_output(
            ["git", "-C", str(repo), "rev-parse", "--short", "HEAD"], text=True
        ).strip()
    except Exception:
        commit = "unknown"

    banner = (
        f"!!! info \"Generated\"\n    Generated by `scripts/gen_param_reference.py` from "
        f"`include/param_prj.h` of firmware **{version}** (commit `{commit}`). "
        f"Edit descriptions in `scripts/param_descriptions.py`, not here.\n"
    )

    # ---------------- parameters ----------------
    lines = ["# Parameters", "", banner,
             "Parameters are settings you change in the web interface or with the terminal "
             "`set` command and store with `save`. Values are checked against min/max "
             "when set through the terminal, web UI or CAN SDO. The **ID** is the stable "
             "number used to store the value in flash and to address it over CAN SDO "
             "(index `0x21hh`, sub-index `ll` for ID `0xhhll`; see [CAN mapping](../user/can-mapping.md)).", ""]
    cats = {}
    for cat, name, unit, mn, mx, df, pid in params:
        cats.setdefault(defines.get(cat, cat), []).append((name, unit, mn, mx, df, pid))
    for cat, rows in cats.items():
        lines += [f"## {cat}", "",
                  "| Name | Unit / options | Min | Max | Default | ID | Description |",
                  "|---|---|---|---|---|---|---|"]
        for name, unit, mn, mx, df, pid in rows:
            u, opts = unit_text(unit, defines)
            if opts:
                u = fmt_options(opts)
            desc = PARAM_DESC.get(name, "(undocumented)")
            lines.append(f"| <a id=\"{name.lower()}\"></a>`{name}` | {u} | {mn} | {mx} | {df} | {pid} | {esc(desc)} |")
        lines.append("")
    (OUT / "parameters.md").write_text("\n".join(lines))

    # ---------------- spot values ----------------
    lines = ["# Spot values", "", banner,
             "Spot values are read-only values the firmware computes and publishes "
             "(the web interface plots them). They are not saved. You can read them with "
             "the terminal `get` command, stream them with `stream`, or send them on CAN "
             "with a CAN map `tx` entry.", "",
             "| Name | Unit / options | ID | Description |", "|---|---|---|---|"]
    for name, unit, vid in values:
        u, opts = unit_text(unit, defines)
        if opts:
            u = fmt_options(opts)
        desc = VALUE_DESC.get(name, "(undocumented)")
        lines.append(f"| <a id=\"{name.lower()}\"></a>`{name}` | {u} | {vid} | {esc(desc)} |")
    lines.append("")
    (OUT / "spot-values.md").write_text("\n".join(lines))

    # ---------------- enums ----------------
    lines = ["# Enumerations", "", banner,
             "These are the option strings the firmware publishes for enumerated "
             "parameters and values. The number is what you `set`; the text is what "
             "the web interface shows.", ""]
    for key in sorted(defines):
        val = defines[key]
        if "=" not in val or key.startswith("CAT_"):
            continue
        lines += [f"## `{key}`", "", fmt_options(val).replace("<br>", "  \n"), ""]
    (OUT / "enums.md").write_text("\n".join(lines))
    print(f"wrote {len(params)} params, {len(values)} values from {version} ({commit})")


if __name__ == "__main__":
    main()
