"""Human-written descriptions for gen_param_reference.py.

Descriptions come from reading the firmware source (V2.41A). Where the
behaviour was inferred rather than tested on a vehicle, the text says so.
"""

PARAM_DESC = {
    # ---- General setup ----
    "Inverter": "Which drive inverter driver to run. `OpenI` sends the OpenInverter control frame 0x3F and reads status from 0x190. `UserCAN` (3) has no driver in `UpdateInv()`, so the previous selection stays active. Changing it calls the old driver's `DeInit()` and re-registers CAN filters.",
    "Vehicle": "Which vehicle integration class to run (dash, ignition, gear selector, CAN spoofing). Note the default `0` is **BMW_E46**, not None. The option list shows `3=None`, but the code's `None` enum is 4, so 3 matches no case and simply keeps the class that was active (the boot default is the internal no-vehicle class).",
    "GearLvr": "Optional CAN gear lever (shifter) class. When a shifter reports a gear, it overrides the forward/reverse inputs, unless the vehicle class already supplies the gear.",
    "Transmission": "Manual or automatic gearbox. Only read by the BMW E39/E46 and E31 classes to drive the dash correctly.",
    "interface": "Charge interface for DC fast charging and/or AC pilot handling: BMW i3 LIM, CHAdeMO, CPC, or FOCCCI (CCS). `Unused` means AC charging is always allowed by the interface.",
    "chargemodes": "Which on-board AC charger driver to use. `EXT_DIGI` uses a digital output to enable an external charger. `Off` disables AC charging.",
    "BMS_Mode": "Which BMS driver to read cell voltage, temperature and charge-current limits from. In this firmware the BMS only gates **charging**; it does not limit drive torque.",
    "ShuntType": "Current/voltage sensor. `ISA` = IVT-S shunt, `SBOX` = BMW i3 contactor box, `VAG` = VW e-box, `ISA_udcsw` = ISA shunt that also sets `udcsw` to 20 V below battery voltage. With `None`, nothing sets `udc` except the Leaf inverter, the Outlander charger or a CAN map; precharge needs `udc` to reach `udcsw`.",
    "InverterCan": "CAN bus used by the inverter driver (CAN1 or CAN2). Both buses run at 500 kbit/s.",
    "VehicleCan": "CAN bus used by the vehicle class and the shifter class.",
    "ShuntCan": "CAN bus the shunt / contactor box is on.",
    "LimCan": "CAN bus used by the charge interface (LIM, CHAdeMO, CPC, FOCCCI).",
    "ChargerCan": "CAN bus used by the AC charger driver.",
    "BMSCan": "CAN bus used by the BMS driver.",
    "OBD2Can": "CAN bus on which the VCU answers OBD2 requests (0x7DF).",
    "CanMapCan": "CAN bus used for user CAN mapping (`can tx`/`can rx`). Read only at boot, so save and reset after changing it.",
    "DCDCCan": "CAN bus used by the DC-DC converter driver.",
    "HeaterCan": "CAN bus used by CAN-controlled cabin heaters.",
    "MotActive": "Toyota hybrid gearboxes only: which motor generators drive (MG1, MG2, both, or blended).",
    "ConfigCANOI": "When set to On with the inverter `OpenI` and the OI board powered, the VCU rewrites the OpenInverter board's CAN map over SDO (node 1): it **clears the board's existing TX and RX maps**, adds frame 0x190 (opmode, udc, speed, heatsink and motor temperature), saves to the board's flash, then sets this parameter back to Off.",
    "UseRS232": "On = keep the terminal UART at a fixed baud rate (for a plain RS232 terminal). Off allows the web interface to switch to a faster baud rate.",
    "DriveInhibit": "`Plug detect` forces Neutral while the charge-port proximity input says a plug is in.",
    # ---- Throttle ----
    "potmin": "ADC reading of throttle channel 1 at rest. Read `pot` with the pedal released and enter it here.",
    "potmax": "ADC reading of throttle channel 1 fully pressed. May be lower than `potmin` for inverted pedals.",
    "pot2min": "ADC reading of throttle channel 2 at rest (dual-channel pedals).",
    "pot2max": "ADC reading of throttle channel 2 fully pressed.",
    "regenrpm": "Motor speed above which full regen is available. Between `regenendrpm` and this value regen tapers linearly.",
    "regenendrpm": "Motor speed below which regen is zero. Must be lower than `regenrpm`; if not, both reset to 1500/100.",
    "regenmax": "Regen torque (percent, negative) at zero pedal (lift-off regen).",
    "regenBrake": "Regen torque (percent, negative) when the brake input is on.",
    "regenramp": "How fast regen torque may build, percent per 10 ms.",
    "potmode": "Single or dual channel throttle. Dual mode cross-checks both channels and falls back to the lower one, capped at 50 %, if they differ by more than 10 %.",
    "dirmode": "How forward/reverse inputs are read: momentary buttons, latching switch, the same reversed, or `DefaultForward` (drive unless reverse input is on).",
    "DirChange": "Restrict forward/reverse changes: `None`, only below `DirChangeRpm`, or below `DirChangeRpm` with the brake pressed. Also drives the `ShiftLockNO` output.",
    "DirChangeRpm": "Motor speed below which a forward/reverse change is accepted when `DirChange` is not None.",
    "reversemotor": "Reverse motor rotation. Only honoured for `RearOutlander`; the firmware forces it back to 0 for other inverters. For an OpenInverter board, reverse rotation is set on the inverter itself.",
    "throtramp": "Throttle ramp-up rate, percent per 10 ms, used below `throtramprpm`.",
    "throtramprpm": "Above this motor speed the throttle ramp is not limited.",
    "revlim": "Motor speed limit; positive torque is reduced as speed approaches it.",
    "revRegen": "Allow regen while in reverse.",
    "udcmin": "Battery voltage below which drive torque is derated (gain 3.5 %/V). 0 disables the check.",
    "udclim": "Over-voltage limit. Above it regen is derated; if exceeded the VCU drops to Off, posts OVERVOLTAGE and, if the motor is stopped, opens the contactors.",
    "idcmax": "Battery discharge current limit for drive torque (needs a shunt). 0 disables.",
    "idcmin": "Battery charge (regen) current limit, negative.",
    "tmphsmax": "Inverter temperature limit. Torque is cut to 50 % within 2 °C above it and to 0 beyond that.",
    "tmpmmax": "Motor temperature limit, same derate behaviour as `tmphsmax`.",
    "throtmax": "Maximum forward torque request, percent.",
    "throtmin": "Maximum regen request, percent (negative).",
    "throtmaxRev": "Maximum torque request in reverse, percent.",
    "throtdead": "Pedal dead zone at the bottom of travel, percent. The rest of travel is rescaled to 0–100 %.",
    "RegenBrakeLight": "Turn on the BrakeLight output when `potnom` is below this (negative) value, i.e. under strong regen.",
    "throtrpmfilt": "Speed filter constant for the throttle (rpm per 10 ms).",
    # ---- Gearbox ----
    "Gear": "Toyota hybrid gearbox ratio selection: low, high, auto, or high forward / low reverse.",
    "OilPump": "Toyota hybrid gearbox oil pump duty, percent.",
    # ---- Cruise ----
    "cruisestep": "Cruise speed step per button press, rpm.",
    "cruiseramp": "Cruise speed ramp rate, rpm per 100 ms.",
    "regenlevel": "Regen level 0–3. When cruise is off, the cruise Set/Resume buttons step this down/up.",
    # ---- Contactor control ----
    "udcsw": "Voltage that `udc` must reach before precharge is considered complete and the main contactor closes. SimpBMS (without a shunt), SBOX, VAG box and ISA_udcsw overwrite this with battery voltage minus 20–30 V.",
    "cruiselight": "Not used by the V2.41A code.",
    "errlights": "Dash warning lights to show (BMW E65 class only).",
    # ---- Communication ----
    "CAN3Speed": "Bit rate of the third CAN port (MCP25625 over SPI): 33.3k, 500k or 100k. In V2.41A CAN3 only passes IDs 0x108/0x109 to the charge interface.",
    # ---- Charger ----
    "BattCap": "Usable pack energy, kWh, used for SOC from the shunt's kWh counter.",
    "Voltspnt": "AC charge target voltage. Charging ends when `udc` ≥ this and `idc` ≤ `IdcTerm`.",
    "Pwrspnt": "AC charge power setpoint, W, passed to the charger driver.",
    "IdcTerm": "Charge termination current, A (see `Voltspnt`).",
    "CCS_ICmd": "Manual DC charge current command (i3 LIM; currently commented out in favour of an automatic ramp).",
    "CCS_ILim": "DC fast charge current limit, A (LIM, CHAdeMO, FOCCCI).",
    "CCS_SOCLim": "DC fast charge SOC limit, percent. Not referenced by the V2.41A code.",
    "SOCFC": "SOC value reported to the DC fast charger (LIM, CHAdeMO). This is a fixed number you set, not the computed SOC.",
    "Chgctrl": "AC charge control: `Enable` (charge whenever plugged in), `Disable`, or `Timer` (start at `Chg_Hrs:Chg_Min` for `Chg_Dur` minutes).",
    "ChgAcVolt": "Assumed AC mains voltage, used by LIM/CPC/FOCCCI to turn the power setpoint into a current.",
    "ChgEff": "Assumed charger efficiency, percent, for the same calculation.",
    "ConfigFoccci": "When On, the VCU configures a FOCCCI board over CAN SDO.",
    # ---- DC-DC ----
    "DCdc_Type": "DC-DC converter driver: none, Tesla Gen2, or Elcon.",
    "DCSetPnt": "DC-DC output voltage setpoint (Tesla Gen2).",
    # ---- BMS ----
    "BMS_Timeout": "Seconds without BMS data before the BMS is treated as invalid (charging stops).",
    "BMS_VminLimit": "Lowest cell voltage at which charging is still allowed.",
    "BMS_VmaxLimit": "Highest cell voltage at which charging is still allowed.",
    "BMS_TminLimit": "Lowest cell temperature for charging.",
    "BMS_TmaxLimit": "Highest cell temperature for charging.",
    # ---- Heater ----
    "Heater": "Cabin heater driver. `PWM` is listed but has no case in `UpdateHeater()` in V2.41A.",
    "Control": "Heater control: disable, enable in Run, or timer (preheat).",
    "HeatPwr": "Heater power request, W.",
    "HeatPercnt": "Heater power in percent (set from the heater potentiometer in scale modes).",
    "HeatPotDir": "How the analogue heater pot is read: on below/above `HeatPotOn`, as on/off (`OF`) or scaled to `HeatPotFull`.",
    "HeatPotOn": "Heater pot ADC threshold for heat on.",
    "HeatPotFull": "Heater pot ADC value for full heat (scale modes).",
    # ---- Clock ----
    "Set_Day": "Set the RTC day of week. Clock values are copied to the RTC only while `Chgctrl` = Disable.",
    "Set_Hour": "Set the RTC hour (see `Set_Day`).",
    "Set_Min": "Set the RTC minute.",
    "Set_Sec": "Set the RTC second.",
    "Chg_Hrs": "Timed charge start hour.",
    "Chg_Min": "Timed charge start minute.",
    "Chg_Dur": "Timed charge duration, minutes.",
    "Pre_Hrs": "Preheat start hour.",
    "Pre_Min": "Preheat start minute.",
    "Pre_Dur": "Preheat duration, minutes.",
    # ---- GPIO ----
    "PumpPWM": "Function of the Oil Pump PWM pin (Timer 1): Toyota oil pump, tachometer pulse output, or speedometer pulse output.",
    "Out1Func": "Function of GP Out 1 (low-side switch). See the output function list.",
    "Out2Func": "Function of GP Out 2.",
    "Out3Func": "Function of GP Out 3.",
    "SL1Func": "Function of the Trans SL1 output when it is not used by a Toyota gearbox.",
    "SL2Func": "Function of the Trans SL2 output.",
    "PWM1Func": "Function of PWM 1 (Timer 3 ch 1, push-pull 12 V). PWM-only functions 15–19 are valid here.",
    "PWM2Func": "Function of PWM 2.",
    "PWM3Func": "Function of PWM 3.",
    "GP12VInFunc": "Function of the GP 12 V input (pin 50). Its default, 12, is above the declared max of 5 and indexes past the end of an array; set it explicitly.",
    "HVReqFunc": "Function of the HV request input pin (51). With defaults it is overridden by `PB3InFunc`, which also defaults to `HVRequest`; set PB1–3 to `NoneIn` if unused.",
    "PB1InFunc": "Function of the Trans PB1 input (pin 42, inverted) when not used by a Toyota gearbox. Defaults to `HVRequest`; set to `NoneIn` if unused.",
    "PB2InFunc": "Function of the Trans PB2 input (pin 41). Same default caveat as `PB1InFunc`.",
    "PB3InFunc": "Function of the Trans PB3 input (pin 40). Same default caveat; with defaults this pin, not pin 51, is the active HV request input.",
    "GPA1Func": "Function of analogue input 1: proximity pilot, brake vacuum sensor, or heater pot.",
    "GPA2Func": "Function of analogue input 2.",
    "ppthresh": "Proximity-pilot ADC threshold. At or below = plug detected.",
    "BrkVacThresh": "Brake vacuum ADC value at which the pump turns off. If it is above `BrkVacHyst` the sensor is treated as rising with vacuum.",
    "BrkVacHyst": "Brake vacuum ADC value at which the pump turns on.",
    "DigiPot1Step": "Digital potentiometer 1 position (0–255). Used by some vehicle classes as a fuel gauge.",
    "DigiPot2Step": "Digital potentiometer 2 position.",
    "FanTemp": "Cooling fan output turns on above this (max of inverter and charger temperature), off 5 °C below.",
    "TachoPPR": "Pulses per revolution for the tacho/speedo pulse output.",
    # ---- Shunt ----
    "IsaInit": "Set to 1 once and reboot to send the ISA shunt its initialisation sequence (new sensor only).",
    # ---- PWM ----
    "Tim3_Presc": "Timer 3 prescaler for the PWM outputs (72 MHz clock).",
    "Tim3_Period": "Timer 3 period for the PWM outputs.",
    "Tim3_1_OC": "PWM 1 compare value (duty) when its function is `PwmTim3`.",
    "Tim3_2_OC": "PWM 2 compare value.",
    "Tim3_3_OC": "PWM 3 compare value.",
    "CP_PWM": "Control-pilot spoof duty (computed from `PilotLim` when a LIM/CPC/FOCCCI is used).",
    "DC_MaxTemp": "PWM temperature gauge duty at `tmphsmax`.",
    "DC_MinTemp": "PWM temperature gauge duty at 0 °C.",
    "DC_MaxSOC": "PWM SOC gauge duty at 100 %.",
    "DC_MinSOC": "PWM SOC gauge duty at 0 %.",
}

VALUE_DESC = {
    "version": "Firmware version string.",
    "opmode": "Current operating mode (Off, Run, Precharge, PchFail, Charge, Preheat).",
    "chgtyp": "Active charge type (Off, AC, DCFC; 4 = external HV request).",
    "lasterr": "Most recent error message.",
    "status": "Bit field: UdcBelowUdcSw, UdcLim, PotPressed and others. Precharge waits until PotPressed, UdcBelowUdcSw and UdcLim are all clear.",
    "CanAct": "CAN activity flag.",
    "TorqDerate": "Why torque is being limited (bit field: UDC low/high, IDC low/high, temperature).",
    "udc": "Battery/DC-link voltage the VCU uses for precharge and limits. Comes from the shunt, the Leaf inverter, or a CAN map.",
    "udc2": "Second voltage channel (shunt U2 or SimpBMS pack voltage).",
    "udc3": "Third shunt voltage channel.",
    "deltaV": "ISA shunt: `udc2/2 - udc3` (pack half balance).",
    "INVudc": "DC voltage reported by the inverter.",
    "power": "Battery power, kW.",
    "idc": "Battery current, A (from the shunt, or SimpBMS when no shunt).",
    "KWh": "Energy counter from the shunt, kWh.",
    "AMPh": "Charge counter from the shunt, Ah.",
    "SOC": "State of charge, percent, from `BattCap` and the shunt's kWh counter.",
    "BMS_Vmin": "Lowest cell voltage from the BMS.",
    "BMS_Vmax": "Highest cell voltage from the BMS.",
    "BMS_Tavg": "Average cell temperature from the BMS.",
    "BMS_Tmin": "Lowest cell temperature from the BMS.",
    "BMS_Tmax": "Highest cell temperature from the BMS.",
    "BMS_ChargeLim": "Charge current the BMS allows (0 stops AC charging).",
    "BMS_MaxInput": "Max charge power reported by the BMS (where supported).",
    "BMS_MaxOutput": "Max discharge power reported by the BMS (informational).",
    "BMS_MaxCharge": "Max charge power, W (where supported).",
    "BMS_Isolation": "Isolation resistance reported by the BMS.",
    "BMS_IsoMeas": "Isolation measurement raw value.",
    "speed": "Motor speed from the inverter, rpm, signed.",
    "Veh_Speed": "Vehicle speed decoded by some vehicle classes.",
    "torque": "Final torque request after processing (tenths of a percent).",
    "pot": "Raw ADC value of throttle channel 1.",
    "pot2": "Raw ADC value of throttle channel 2.",
    "potbrake": "Not set by the V2.41A code.",
    "brakepressure": "Not set by the V2.41A code.",
    "potnom": "Processed throttle command, percent (-100 to 100). Negative is regen.",
    "dir": "Selected direction: -1 reverse, 0 neutral, 1 drive, 2 park.",
    "tmphs": "Inverter temperature.",
    "tmpm": "Motor temperature.",
    "tmpaux": "ISA shunt temperature.",
    "uaux": "12 V supply voltage measured on the board.",
    "canio": "Digital inputs received over CAN (bit field). Clears with a CAN timeout error if the bus stops.",
    "FrontRearBal": "Front/rear torque balance from the vehicle class (100 = all front).",
    "cruisespeed": "Cruise control target speed, rpm.",
    "cruisestt": "Cruise button state from the vehicle class.",
    "din_HVreq": "HV request input state.",
    "din_start": "Start input state (pin or CAN).",
    "din_brake": "Brake input state (pin or CAN).",
    "din_forward": "Forward input state.",
    "din_reverse": "Reverse input state.",
    "din_bms": "BMS flag received via CAN io.",
    "din_12Vgp": "GP 12 V input state.",
    "ShiftLock": "Shift-lock release output request.",
    "handbrk": "Handbrake state (vehicle classes that read it).",
    "Gear1": "Toyota gearbox position input 1.",
    "Gear2": "Toyota gearbox position input 2.",
    "Gear3": "Toyota gearbox position input 3.",
    "T15Stat": "Ignition (T15) status as reported by the vehicle class `Ready()`.",
    "InvStat": "Inverter status reported by the inverter driver.",
    "GearFB": "Toyota gearbox ratio feedback.",
    "CableLim": "Charge cable current limit (from proximity pilot / charge interface).",
    "PilotLim": "Control pilot current limit.",
    "PlugDet": "Charge plug detected.",
    "PilotTyp": "Pilot state from the charge interface.",
    "CCS_I_Avail": "DC charger current available.",
    "CCS_V_Avail": "DC charger voltage available.",
    "CCS_I": "DC charger present current.",
    "CCS_Ireq": "DC current requested by the VCU.",
    "CCS_V": "DC charger present voltage.",
    "CCS_V_Min": "DC charger minimum voltage.",
    "CCS_V_Con": "Voltage at the DC charge contactors.",
    "hvChg": "DC charge HV flag.",
    "CCS_COND": "DC charger condition.",
    "CCS_State": "DC charge state machine step.",
    "CP_DOOR": "Charge port door state.",
    "CCS_Contactor": "DC charge contactor state.",
    "Day": "RTC day of week.",
    "Hour": "RTC hour.",
    "Min": "RTC minute.",
    "Sec": "RTC second.",
    "ChgT": "Timed-charge minutes remaining.",
    "U12V": "12 V system voltage reported by a DC-DC or vehicle class.",
    "I12V": "12 V current reported by a DC-DC.",
    "ChgTemp": "Charger temperature.",
    "AC_Volts": "AC input voltage reported by the charger.",
    "AC_Amps": "AC input current reported by the charger.",
    "canctr": "Rolling counter used in the OpenInverter control frame (Run mode only).",
    "cpuload": "Scheduler CPU load, percent.",
    "PPVal": "Proximity pilot ADC reading.",
    "BrkVacVal": "Brake vacuum sensor ADC reading.",
    "HtPotVal": "Heater pot ADC reading.",
    "HeatReq": "Heat requested (from input or pot).",
    "tmpheater": "Heater temperature.",
    "udcheater": "Heater HV voltage.",
    "powerheater": "Heater power.",
    "VehLockSt": "Vehicle lock state (classes that decode it).",
    "uptime": "RTC counter, seconds since power-up.",
    "MG1Torque": "Toyota MG1 torque (debug).",
    "MG2Torque": "Toyota MG2 torque (debug).",
    "MG1Raw": "Toyota inverter raw value (debug).",
    "MG2Raw": "Toyota inverter raw value (debug).",
    "MG1Raw2": "Toyota inverter raw value (debug).",
    "DMA_RxComplete": "Toyota sync-serial DMA receive flag (debug).",
    "DMA_TxComplete": "Toyota sync-serial DMA transmit flag (debug).",
    "DMA_RxTimeout": "Toyota sync-serial receive timeouts (debug).",
    "DMA_ConsecFail": "Toyota sync-serial consecutive failures (debug).",
    "HTM_State": "Toyota inverter HTM state (debug).",
}
